#!/bin/bash
# GitHub一键部署脚本 - 个人网站
# 使用方法: ./github-deploy.sh
# 预计时间: 3-5分钟

PROJECT_DIR="～/.openclaw/workspace/财富自由之路/personal-website"
REPO_NAME="personal-website"
USERNAME="petterobam"

echo "🚀 开始GitHub一键部署..."
echo "📁 项目目录: $PROJECT_DIR"
echo "🏷️  仓库名称: $REPO_NAME"
echo "👤 用户名: $USERNAME"
echo ""

# 检查项目目录
if [ ! -d "$PROJECT_DIR" ]; then
    echo "❌ 错误: 项目目录不存在"
    echo "请确保项目路径正确: $PROJECT_DIR"
    exit 1
fi

# 进入项目目录
echo "🔍 检查项目目录..."
cd "$PROJECT_DIR"

# 检查Git状态
if [ ! -d ".git" ]; then
    echo "🔧 初始化Git仓库..."
    git init
    echo "✅ Git仓库初始化完成"
else
    echo "✅ Git仓库已存在"
fi

# 检查是否有待提交的更改
echo "📋 检查Git状态..."
git status --porcelain

if [ -z "$(git status --porcelain)" ]; then
    echo "✅ 没有待提交的更改，代码已是最新"
else
    echo "📝 检测到待提交的更改，正在添加文件..."
    git add .
    echo "✅ 文件已添加到Git暂存区"
fi

# 创建提交
echo "🔄 创建提交..."
git commit -m "Initial commit: Personal website deployment

- VuePress-based personal website
- GitHub Actions auto-deployment
- Ready for Pages publishing

🤖 Generated by wealth-freedom automation system - 2026-04-05"

if [ $? -eq 0 ]; then
    echo "✅ 提交完成"
else
    echo "⚠️  没有需要提交的更改，跳过提交"
fi

# 检查远程仓库
echo "🔗 检查远程仓库配置..."
if git remote -v | grep -q "origin.*github.com"; then
    echo "✅ 远程仓库已配置"
    git remote -v
else
    echo "🔗 添加远程仓库..."
    git remote remove origin 2>/dev/null || true
    git remote add origin "https://github.com/$USERNAME/$REPO_NAME.git"
    echo "✅ 远程仓库已添加: https://github.com/$USERNAME/$REPO_NAME.git"
fi

# 推送到GitHub
echo "🚀 推送到GitHub..."
echo "⏳ 正在推送代码，这可能需要1-2分钟..."

# 检查当前分支
CURRENT_BRANCH=$(git branch --show-current)
if [ -z "$CURRENT_BRANCH" ]; then
    CURRENT_BRANCH="main"
    git branch -M main
    echo "🏷️  分支重命名为: main"
fi

git push -u origin $CURRENT_BRANCH

if [ $? -eq 0 ]; then
    echo "🎉 代码推送成功！"
    echo "✅ GitHub仓库创建完成"
else
    echo "❌ 推送失败，请检查:"
    echo "   1. GitHub是否已创建同名仓库"
    echo "   2. 是否已配置GitHub认证"
    echo "   3. 网络连接是否正常"
    exit 1
fi

echo ""
echo "🎉 GitHub部署准备完成！"
echo "📋 下一步操作:"
echo ""
echo "1️⃣ 创建GitHub仓库（如果尚未创建）:"
echo "   📍 访问: https://github.com/new"
echo "   🏷️  仓库名称: $REPO_NAME"
echo "   🔓 公开/私有: 公开（GitHub Pages需要）"
echo "   ⚠️  不要勾选'Add a README file'、'Add .gitignore'、'Add a license'"
echo ""
echo "2️⃣ 启用GitHub Pages:"
echo "   📍 访问: https://github.com/$USERNAME/$REPO_NAME/settings/pages"
echo "   📄 Source选择: GitHub Actions"
echo "   💾 等待GitHub Actions自动部署"
echo ""
echo "3️⃣ 验证部署成功:"
echo "   📍 访问: https://$USERNAME.github.io/$REPO_NAME/"
echo "   ✅ 确认网站正常显示"
echo ""
echo "4️⃣ 发布技术文章:"
echo "   📝 查看: 财富自由之路/文章发布/"
echo "   📋 使用发布清单发布3篇文章"
echo ""
echo "⏱️  预计完成时间: 5-10分钟"
echo "🎯 总体进度: 99% → 100%"
echo ""
echo "💡 提示: 如果遇到问题，请查看产品研发目录下的故障排除指南"

# 创建部署完成标志
echo "📊 记录部署状态..."
DEPLOY_LOG_FILE="～/.openclaw/workspace/财富自由之路/产品研发/deployment-status-$(date +%Y%m%d-%H%M%S).md"
cat > "$DEPLOY_LOG_FILE" << EOF
# GitHub部署状态记录

**部署时间**: $(date '+%Y-%m-%d %H:%M:%S')
**项目名称**: $REPO_NAME
**GitHub用户**: $USERNAME
**部署状态**: ✅ 成功
**操作脚本**: github-deploy.sh
**代码仓库**: https://github.com/$USERNAME/$REPO_NAME

## 部署步骤

1. ✅ Git仓库初始化/检查
2. ✅ 文件添加到暂存区  
3. ✅ 创建提交
4. ✅ 配置远程仓库
5. ✅ 推送到GitHub

## 下一步操作

1. 创建GitHub仓库（如果尚未创建）
2. 启用GitHub Pages
3. 验证网站部署
4. 发布技术文章

---
*自动生成 by wealth-freedom automation system*
EOF

echo "✅ 部署状态已记录: $DEPLOY_LOG_FILE"